Update buildJreArm64.yml

diff --git a/.github/workflows/buildJreArm64.yml b/.github/workflows/buildJreArm64.yml
--- a/.github/workflows/buildJreArm64.yml
+++ b/.github/workflows/buildJreArm64.yml
@@ -34,7 +34,12 @@ jobs:
       run: |
         mkdir -p $HOME/.ops/bin
         sudo ln -sf /usr/bin/qemu-aarch64-static $HOME/.ops/bin/qemu-aarch64
-
+         # Controllo se il binario è accessibile
+        echo "QEMU aarch64 path: $(which qemu-aarch64 || echo 'Not found')"
+    
+        # Versione QEMU
+        qemu-aarch64 --version
+        
     # Install ops
     - name: Install ops (NanoVMs)
       run: |
